### ISSUE TITLE
Jobs Reborn Event Triggers

### ISSUE THREAD

**Issue by Zamoar** [CoolLord22/OtherDrops1.13#15]
**Is your feature request related to a problem? Please describe.**
The lack of having this feature elsewhere.

**Describe the solution you'd like**
If possible, make it so that JobsReborn events like:

JobsLevelUpEvent
JobsPaymentEvent
JobsExpGainEvent

could be used as triggers.

**Describe alternatives you've considered**
The only other alternative that might work is with Skript using the TuSKe addon. Otherdrops just seems like it's the perfect home for this sort of functionality though.

**Additional context**
I just want to have events where if players are active in their jobs, they can get special rewards. Whether this be event crate keys, or just some nice loot.

**Comment by CoolLord22** [comment]
Triggers have been added! `JOBS_LEVEL_UP, JOBS_PAYMENT, JOBS_EXP_GAIN` and new condition for job name, use `jobs: [list, of, jobs]` supports negative job matching as well.
