### ISSUE TITLE
Data for Replacetool

### ISSUE THREAD

**Issue by Reeferx7** [CoolLord22/OtherDrops1.13#9]
**Is your feature request related to a problem? Please describe.**
Add more data for replacetool like the tool: enchants lore name etc

**Comment by CoolLord22** [comment]
Format for specifying replacetool is now as follows: `ITEM/q#1` where `<ITEM>` is the material you want to replace with, and `<1>` is a quantity (supports quantity range ie `2-4`). Do note this does support custom name and lores as well; see following example: `DIRT@!unbreaking#1!~&aLucky Dirt/q#1-5`
